import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const baseUrl = process.env.BDO_TEST_URL ?? "http://127.0.0.1:18769/";
const python = process.env.PYTHON ?? "python";
const chromePath = process.env.BDO_CHROME ?? "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const profile = await mkdtemp(join(tmpdir(), "bdo-t010p2-roi-browser-"));
const database = join(profile, "isolated.sqlite3");
const port = new URL(baseUrl).port || "18769";
const pythonCode = `from local_app.backend.app import create_app; create_app(r'${database}', testing=True).run(host='127.0.0.1', port=${Number(port)}, use_reloader=False, threaded=True)`;
let server; let chrome; let socket; let send;
async function waitFor(predicate, label, timeoutMs = 20000) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) { const value = await predicate(); if (value) return value; await new Promise((resolveWait) => setTimeout(resolveWait, 100)); }
  throw new Error(`Timed out waiting for ${label}`);
}
try {
  server = spawn(python, ["-B", "-c", pythonCode], { cwd: root, stdio: "ignore", windowsHide: true, env: { ...process.env, LOCALAPPDATA: profile, PYTHONDONTWRITEBYTECODE: "1" } });
  await waitFor(async () => { try { return (await fetch(`${baseUrl}api/health`)).ok; } catch { return false; } }, "isolated app server");
  chrome = spawn(chromePath, ["--headless=new", "--no-sandbox", "--disable-gpu", "--no-first-run", "--disable-extensions", "--disable-background-networking", "--window-size=1200,900", "--remote-debugging-port=0", "--remote-allow-origins=*", `--user-data-dir=${join(profile, "chrome-profile")}`, "about:blank"], { stdio: "ignore", windowsHide: true });
  const activePortPath = join(profile, "chrome-profile", "DevToolsActivePort");
  const activePortText = await waitFor(async () => { try { return await readFile(activePortPath, "utf8"); } catch { return false; } }, "Chrome DevTools endpoint");
  const debugPort = activePortText.trim().split(/\r?\n/)[0];
  const targetResponse = await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(baseUrl)}`, { method: "PUT" });
  assert.equal(targetResponse.ok, true);
  const target = await targetResponse.json();
  socket = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolveOpen, reject) => { socket.addEventListener("open", resolveOpen, { once: true }); socket.addEventListener("error", reject, { once: true }); });
  const pending = new Map(); let nextId = 0;
  socket.addEventListener("message", (event) => { const message = JSON.parse(event.data); if (!message.id || !pending.has(message.id)) return; const waiter = pending.get(message.id); pending.delete(message.id); message.error ? waiter.reject(new Error(message.error.message)) : waiter.resolve(message.result); });
  send = (method, params = {}) => new Promise((resolveMessage, reject) => { const id = ++nextId; pending.set(id, { resolve: resolveMessage, reject }); socket.send(JSON.stringify({ id, method, params })); });
  const evaluate = async (expression) => { const result = await send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result?.value; };
  await send("Page.enable"); await send("Runtime.enable"); await send("DOM.enable");
  await waitFor(async () => (await evaluate("document.querySelector('#app-content')?.getAttribute('aria-busy')")) === "false", "app bootstrap");
  const initial = await (await fetch(`${baseUrl}api/bootstrap`)).json();
  await evaluate(`(() => {
    const source=document.createElement('canvas'); source.width=640; source.height=360;
    const context=source.getContext('2d'); let frame=0;
    const paint=()=>{context.fillStyle=frame++%2?'#183448':'#9a351e';context.fillRect(0,0,640,360);context.fillStyle='#fff';context.fillRect(80,60,170,90);}; paint();
    const timer=setInterval(paint,100);
    let calls=0; const streams=[];
    Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:async options=>{window.__screenRequestOptions=(window.__screenRequestOptions||[]).concat([options]);calls++;const stream=source.captureStream(30);streams.push(stream);return stream;}});
    window.__roiMock={source,streams,timer,get calls(){return calls;}};
  })()`);
  await evaluate("document.querySelector('#connect-screen-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#screen-capture-session')?.dataset.state==='CONNECTED'"), "shared stream connection");
  await evaluate("document.querySelector('#open-trade-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.open && document.querySelector('[data-role=trade-preview-video]').videoWidth===640"), "Trade live preview");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-preview-video]').srcObject===window.__roiMock.streams[0]"), true, "Trade preview uses the shared stream");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-roi]').hidden"), false);
  assert.equal(await evaluate("document.querySelectorAll('[data-role=trade-roi] [data-roi-handle]').length"), 8);
  const initialRoi = await evaluate("JSON.stringify({left:parseFloat(document.querySelector('[data-role=trade-roi]').style.left),top:parseFloat(document.querySelector('[data-role=trade-roi]').style.top),width:parseFloat(document.querySelector('[data-role=trade-roi]').style.width),height:parseFloat(document.querySelector('[data-role=trade-roi]').style.height),content:(()=>{const v=document.querySelector('[data-role=trade-preview-video]'),e=document.querySelector('[data-role=trade-preview-stage]'),s=e.getBoundingClientRect(),w0=e.clientWidth,h0=e.clientHeight,scale=Math.min(w0/v.videoWidth,h0/v.videoHeight),w=v.videoWidth*scale,h=v.videoHeight*scale;return {left:e.clientLeft+(w0-w)/2,top:e.clientTop+(h0-h)/2,width:w,height:h}})()})").then(JSON.parse);
  assert.ok(Math.abs(initialRoi.top - (initialRoi.content.top + initialRoi.content.height*.1)) < 1, `normalized default ROI follows letterboxed content rect ${JSON.stringify(initialRoi)}`);
  const beforeMoveLeft = initialRoi.left;
  const stageRect = await evaluate("JSON.stringify((()=>{const s=document.querySelector('[data-role=trade-preview-stage]').getBoundingClientRect(),r=document.querySelector('[data-role=trade-roi]').getBoundingClientRect();return {x:r.left+40,y:r.top+35,sx:s.left,sy:s.top}})())").then(JSON.parse);
  await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: stageRect.x, y: stageRect.y });
  await send("Input.dispatchMouseEvent", { type: "mousePressed", x: stageRect.x, y: stageRect.y, button: "left", buttons: 1, clickCount: 1 });
  await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: stageRect.x+30, y: stageRect.y+20, button: "left", buttons: 1 });
  await send("Input.dispatchMouseEvent", { type: "mouseReleased", x: stageRect.x+30, y: stageRect.y+20, button: "left", buttons: 0, clickCount: 1 });
  const movedLeft = await evaluate("parseFloat(document.querySelector('[data-role=trade-roi]').style.left)");
  assert.ok(movedLeft > beforeMoveLeft+15, "ROI pointer drag moves the box");
  const se = await evaluate("JSON.stringify((()=>{const r=document.querySelector('[data-role=trade-roi]').getBoundingClientRect();return {x:r.right-1,y:r.bottom-1}})())").then(JSON.parse);
  await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: se.x, y: se.y }); await send("Input.dispatchMouseEvent", { type: "mousePressed", x: se.x, y: se.y, button: "left", buttons: 1, clickCount: 1 }); await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: se.x+24, y: se.y+18, button: "left", buttons: 1 }); await send("Input.dispatchMouseEvent", { type: "mouseReleased", x: se.x+24, y: se.y+18, button: "left", buttons: 0, clickCount: 1 });
  const resized = await evaluate("JSON.stringify((()=>{const r=document.querySelector('[data-role=trade-roi]').getBoundingClientRect();return {width:r.width,height:r.height}})())").then(JSON.parse);
  assert.ok(resized.width > initialRoi.width && resized.height > initialRoi.height, "SE handle resizes the ROI");
  const normalizedBeforePreviewResize = await evaluate("document.querySelector('[data-role=trade-roi]').dataset.normalized");
  await evaluate("document.querySelector('[data-role=trade-preview-stage]').style.width='80%'");
  await new Promise((resolveWait) => setTimeout(resolveWait, 100));
  assert.equal(await evaluate("document.querySelector('[data-role=trade-roi]').dataset.normalized"), normalizedBeforePreviewResize, "preview CSS resize preserves normalized ROI authority");
  await evaluate("document.querySelector('[data-action=capture-trade-roi]').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.dataset.queueLength==='1'"), "first ROI capture queued");
  const first = await evaluate("JSON.stringify((()=>{const li=document.querySelector('.capture-draft-item'),img=li.querySelector('img');return {id:li.dataset.captureId,batch:li.dataset.batchId,evidence:JSON.parse(li.dataset.regionEvidence),width:img.naturalWidth,height:img.naturalHeight,label:li.textContent,status:li.querySelector('.capture-draft-state').textContent}})())").then(JSON.parse);
  assert.ok(first.id && first.batch && first.width < 640 && first.height < 360, "queue preview dimensions represent the cropped ROI");
  assert.equal(first.width, first.evidence.sourceRect.width); assert.equal(first.height, first.evidence.sourceRect.height);
  assert.equal(first.evidence.sourceFrame.width, 640); assert.equal(first.evidence.sourceFrame.height, 360);
  assert.match(first.label,/선택 영역/); assert.match(first.status,/인식 대기/);
  await evaluate("window.__roiMock.source.getContext('2d').fillStyle='#42a66b';window.__roiMock.source.getContext('2d').fillRect(0,0,640,360)");
  await evaluate("document.querySelector('[data-action=capture-trade-roi]').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.dataset.queueLength==='2'"), "second ROI capture queued");
  const rows = await evaluate("JSON.stringify([...document.querySelectorAll('.capture-draft-item')].map(li=>({id:li.dataset.captureId,batch:li.dataset.batchId,evidence:JSON.parse(li.dataset.regionEvidence)})))").then(JSON.parse);
  assert.notEqual(rows[0].id, rows[1].id); assert.equal(rows[0].batch, rows[1].batch); assert.notDeepEqual(rows[0].evidence.sourceRect, {x:0,y:0,width:640,height:360});
  await evaluate("document.querySelector('.capture-draft-item button').click()");
  assert.equal(await evaluate("document.querySelector('#trade-capture-dialog').dataset.queueLength"), "1");
  const keptId = await evaluate("document.querySelector('.capture-draft-item').dataset.captureId");
  const roiBeforeClose = await evaluate("document.querySelector('[data-role=trade-roi]').style.cssText");
  await evaluate("document.querySelector('#trade-capture-dialog [data-close-trade-capture]').click()");
  assert.equal(await evaluate("document.querySelector('#screen-capture-session').dataset.state"), "CONNECTED");
  assert.equal(await evaluate("window.__roiMock.streams[0].getVideoTracks()[0].readyState"), "live");
  await evaluate("document.querySelector('#open-trade-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.open && document.querySelector('.capture-draft-item')?.dataset.captureId"), "dialog reopen queue");
  assert.equal(await evaluate("document.querySelector('.capture-draft-item').dataset.captureId"), keptId);
  const reopenDebug = await evaluate("JSON.stringify({same:document.querySelector('[data-role=trade-preview-video]').srcObject===window.__roiMock.streams[0],src:!!document.querySelector('[data-role=trade-preview-video]').srcObject,state:document.querySelector('#screen-capture-session').dataset.state,tracks:window.__roiMock.streams[0].getVideoTracks()[0].readyState})");
  assert.equal(JSON.parse(reopenDebug).same, true, reopenDebug);
  assert.equal(await evaluate("document.querySelector('[data-role=trade-roi]').style.cssText"), roiBeforeClose, "ROI remains normalized and positioned after reopen");
  await evaluate("document.querySelector('[data-action=clear-trade-queue]').click()");
  assert.equal(await evaluate("document.querySelector('#trade-capture-dialog').dataset.queueLength"), "0");
  assert.equal(await evaluate("document.querySelector('#screen-capture-session').dataset.state"), "CONNECTED", "clear keeps the stream alive");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-roi]').dataset.normalized"), normalizedBeforePreviewResize, "clear keeps the ROI selection");
  await evaluate("document.querySelector('[data-action=capture-trade-roi]').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.dataset.queueLength==='1'"), "new batch after clear");
  const freshBatch = await evaluate("document.querySelector('.capture-draft-item').dataset.batchId"); assert.notEqual(freshBatch, first.batch);
  await evaluate("document.querySelector('[data-action=clear-trade-queue]').click()");
  const tradeRowsBefore = await evaluate("document.querySelector('#trade-list-root').textContent");
  await evaluate("document.querySelector('#trade-capture-dialog [data-close-trade-capture]').click()");
  await evaluate("document.querySelector('#open-warehouse-scan').click()");
  await waitFor(async () => evaluate("document.querySelector('#warehouse-scan-dialog')?.open"), "Warehouse dialog");
  await evaluate("document.querySelector('[data-screen-capture=warehouse]').click()");
  await waitFor(async () => evaluate("document.querySelector('#warehouse-scan-dialog')?.dataset.queueLength==='1'"), "Warehouse full frame capture");
  assert.match(await evaluate("document.querySelector('.warehouse-scan-message').textContent"), /640×360 프레임/);
  assert.equal(await evaluate("document.querySelector('#trade-list-root').textContent"), tradeRowsBefore, "no Trade rows created");
  const after = await (await fetch(`${baseUrl}api/bootstrap`)).json(); assert.equal(after.revision, initial.revision); assert.deepEqual(after.inventory, initial.inventory);
  assert.deepEqual(await evaluate("JSON.stringify(window.__screenRequestOptions)").then(JSON.parse), [{video:{displaySurface:"window"},audio:false}], "Trade did not request a separate display stream");
  await evaluate("document.querySelector('#warehouse-scan-dialog [data-action=close]').click()");
  await evaluate("document.querySelector('#open-trade-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.open"), "Trade dialog for track-ended case");
  await evaluate("document.querySelector('#disconnect-screen-capture').click()");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-preview-video]').srcObject===null"), true);
  await evaluate("document.querySelector('#connect-screen-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#screen-capture-session')?.dataset.state==='CONNECTED' && window.__roiMock.calls===2"), "explicit reconnect before track-ended case");
  await evaluate("document.querySelector('[data-action=capture-trade-roi]').click()");
  await waitFor(async () => evaluate("document.querySelector('#trade-capture-dialog')?.dataset.queueLength==='1'"), "capture before track end");
  const callsBeforeEnd = await evaluate("window.__roiMock.calls");
  await evaluate("window.__roiMock.streams.at(-1).getVideoTracks()[0].dispatchEvent(new Event('ended'))");
  assert.equal(await evaluate("document.querySelector('#screen-capture-session').dataset.state"), "DISCONNECTED");
  assert.equal(await evaluate("document.querySelector('#trade-capture-dialog').dataset.queueLength"), "1", "track end keeps queued drafts");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-preview-video]').srcObject===null"), true);
  assert.equal(await evaluate("window.__roiMock.calls"), callsBeforeEnd, "track end never requests automatic reconnect");
  await evaluate("document.querySelector('#connect-screen-capture').click()");
  await waitFor(async () => evaluate("document.querySelector('#screen-capture-session')?.dataset.state==='CONNECTED' && window.__roiMock.calls===3"), "explicit reconnect after track end");
  assert.equal(await evaluate("document.querySelector('#trade-capture-dialog').dataset.queueLength"), "1", "reconnect preserves queued drafts");
  assert.equal(await evaluate("document.querySelector('[data-role=trade-preview-video]').srcObject===window.__roiMock.streams.at(-1)"), true);
  console.log(JSON.stringify({ ok:true, testType:"AUTOMATED_MOCK_PASS", chrome:"headless", previewSharedStream:"PASS", separateGetDisplayMedia:"NO", defaultRoiAndLetterbox:"PASS", pointerMove:"PASS", resizeEightHandlesPresentAndSEInteraction:"PASS", roiOnlyPngDimensionsAndProvenance:"PASS", repeatedBatchCapture:"PASS", removeAndClear:"PASS", dialogQueueStreamRoiPreserved:"PASS", disconnectReconnectTrackEnded:"PASS", noAutomaticReconnect:"PASS", warehouseFullFrameUnchanged:"PASS", mainDbSemanticStateUnchanged:"PASS", actualPermissionPicker:"PENDING", actualBDOWindow:"PENDING" },null,2));
} finally {
  try { if (socket?.readyState===WebSocket.OPEN) await Promise.race([send("Browser.close"),new Promise(r=>setTimeout(r,1000))]); } catch {}
  try { socket?.close(); } catch {}
  for (const child of [chrome,server]) if (child?.pid) { try { child.kill(); await Promise.race([new Promise(r=>child.once("exit",r)),new Promise(r=>setTimeout(r,1500))]); } catch {} }
  await new Promise(r=>setTimeout(r,500)); try { await rm(profile,{recursive:true,force:true,maxRetries:4,retryDelay:250}); } catch {}
}
